services:
  mysql:
    image: mysql:8.0
    container_name: skooly_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skooly_db
      MYSQL_USER: skooly
      MYSQL_PASSWORD: skooly123
    ports:
      - "3306:3306"
    volumes:
      - skooly_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  skooly_mysql_data:
