package com.skooly.enums;

public enum NotificationType {
	ACCOUNT_PENDING_APPROVAL,
	ACCOUNT_APPROVED,
	ACCOUNT_REJECTED,
	ACCOUNT_CREATED,
	PASSWORD_CHANGED,
	OTP_SENT,
	NEW_DEVICE_LOGIN,
	// Future use:
	ASSIGNMENT_GRADED,
	FEE_DUE,
	ATTENDANCE_MARKED,
	EXAM_SCHEDULED
}