server:
  port: 8080
  servlet:
    context-path: /
  address: 0.0.0.0 #this enables other device access on same network

spring:
  application:
    name: skooly

  datasource:
    url: jdbc:mysql://localhost:3306/skooly_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  # ── Mail (dummy for now — replace with real credentials later) ────────────────
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 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
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ── JWT ───────────────────────────────────────────────────────────────────────
jwt:
  secret: a3f8b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0
  access-token-expiry: 900000        # 15 minutes in milliseconds
  refresh-token-expiry: 604800000    # 7 days in milliseconds
  #JWT secret — when you replace it later use a Base64 encoded string of at least 256 bits. You can generate one with:
  # secret: YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZg==

# ── OTP ───────────────────────────────────────────────────────────────────────
otp:
  expiry-minutes: 5
  length: 6

# ── CORS (Vite local dev) ─────────────────────────────────────────────────────
cors:
  allowed-origins: http://localhost:5173, https://skooly.vercel.app

# ── Swagger Ui ───────────────────────────────────────────────────────────────────────
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    com.skooly: DEBUG

# 172.24.176.1:8080
# http://172.24.176.1:8080/api/v1/schools